CREATE TABLE PUBLIC.BATCH_REQUEST (
  BATCH_REQUEST_ID VARCHAR(100) NOT NULL,
  BATCH_REQUEST_NAME VARCHAR(100) NOT NULL,
  PROCESS_HALT_FLG CHAR(1) NOT NULL,
  PROCESS_ACTIVE_FLG CHAR(1) NOT NULL,
  SERVICE_AVAILABLE CHAR(1) NOT NULL,
  RESUME_POINT BIGINT NOT NULL,
  PRIMARY KEY (BATCH_REQUEST_ID)
);
COMMENT ON table PUBLIC.BATCH_REQUEST is '�o�b�`���N�G�X�g';
COMMENT ON column PUBLIC.BATCH_REQUEST.BATCH_REQUEST_ID is '�o�b�`���N�G�X�gID';
COMMENT ON column PUBLIC.BATCH_REQUEST.BATCH_REQUEST_NAME is '���N�G�X�g��';
COMMENT ON column PUBLIC.BATCH_REQUEST.PROCESS_HALT_FLG is '������~�t���O';
COMMENT ON column PUBLIC.BATCH_REQUEST.PROCESS_ACTIVE_FLG is '�A�N�e�B�u�t���O';
COMMENT ON column PUBLIC.BATCH_REQUEST.SERVICE_AVAILABLE is '�T�[�r�X�񋟉ۏ��';
COMMENT ON column PUBLIC.BATCH_REQUEST.RESUME_POINT is '���W���[���|�C���g';
CREATE TABLE PUBLIC.BUSINESS_DATE (
  SEGMENT_ID CHAR(2) NOT NULL,
  BIZ_DATE CHAR(8) NOT NULL,
  PRIMARY KEY (SEGMENT_ID)
);
COMMENT ON table PUBLIC.BUSINESS_DATE is '�Ɩ����t';
COMMENT ON column PUBLIC.BUSINESS_DATE.SEGMENT_ID is '�Z�O�����gID';
COMMENT ON column PUBLIC.BUSINESS_DATE.BIZ_DATE is '�Ɩ����t';
CREATE TABLE PUBLIC.CODE_NAME (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG CHAR(2) NOT NULL,
  SORT_ORDER SMALLINT NOT NULL,
  CODE_NAME VARCHAR(50) NOT NULL,
  SHORT_NAME VARCHAR(50),
  OPTION01 VARCHAR(50),
  OPTION02 VARCHAR(50),
  OPTION03 VARCHAR(50),
  OPTION04 VARCHAR(50),
  OPTION05 VARCHAR(50),
  OPTION06 VARCHAR(50),
  OPTION07 VARCHAR(50),
  OPTION08 VARCHAR(50),
  OPTION09 VARCHAR(50),
  OPTION10 VARCHAR(50),
  PRIMARY KEY (CODE_ID, CODE_VALUE, LANG)
);
COMMENT ON table PUBLIC.CODE_NAME is '�R�[�h����';
COMMENT ON column PUBLIC.CODE_NAME.CODE_ID is '�R�[�hID';
COMMENT ON column PUBLIC.CODE_NAME.CODE_VALUE is '�R�[�h�l';
COMMENT ON column PUBLIC.CODE_NAME.LANG is '����';
COMMENT ON column PUBLIC.CODE_NAME.SORT_ORDER is '�\�[�g��';
COMMENT ON column PUBLIC.CODE_NAME.CODE_NAME is '����';
COMMENT ON column PUBLIC.CODE_NAME.SHORT_NAME is '�R�[�h����';
COMMENT ON column PUBLIC.CODE_NAME.OPTION01 is '�I�v�V��������01';
COMMENT ON column PUBLIC.CODE_NAME.OPTION02 is '�I�v�V��������02';
COMMENT ON column PUBLIC.CODE_NAME.OPTION03 is '�I�v�V��������03';
COMMENT ON column PUBLIC.CODE_NAME.OPTION04 is '�I�v�V��������04';
COMMENT ON column PUBLIC.CODE_NAME.OPTION05 is '�I�v�V��������05';
COMMENT ON column PUBLIC.CODE_NAME.OPTION06 is '�I�v�V��������06';
COMMENT ON column PUBLIC.CODE_NAME.OPTION07 is '�I�v�V��������07';
COMMENT ON column PUBLIC.CODE_NAME.OPTION08 is '�I�v�V��������08';
COMMENT ON column PUBLIC.CODE_NAME.OPTION09 is '�I�v�V��������09';
COMMENT ON column PUBLIC.CODE_NAME.OPTION10 is '�I�v�V��������10';
CREATE TABLE PUBLIC.CODE_PATTERN (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  PATTERN01 CHAR(1) NOT NULL,
  PATTERN02 CHAR(1),
  PATTERN03 CHAR(1),
  PATTERN04 CHAR(1),
  PATTERN05 CHAR(1),
  PATTERN06 CHAR(1),
  PATTERN07 CHAR(1),
  PATTERN08 CHAR(1),
  PATTERN09 CHAR(1),
  PATTERN10 CHAR(1),
  PATTERN11 CHAR(1),
  PATTERN12 CHAR(1),
  PATTERN13 CHAR(1),
  PATTERN14 CHAR(1),
  PATTERN15 CHAR(1),
  PATTERN16 CHAR(1),
  PATTERN17 CHAR(1),
  PATTERN18 CHAR(1),
  PATTERN19 CHAR(1),
  PATTERN20 CHAR(1),
  PRIMARY KEY (CODE_ID, CODE_VALUE)
);
COMMENT ON table PUBLIC.CODE_PATTERN is '�R�[�h�p�^�[��';
COMMENT ON column PUBLIC.CODE_PATTERN.CODE_ID is '�R�[�hID';
COMMENT ON column PUBLIC.CODE_PATTERN.CODE_VALUE is '�R�[�h�l';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN01 is '�p�^�[��01';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN02 is '�p�^�[��02';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN03 is '�p�^�[��03';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN04 is '�p�^�[��04';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN05 is '�p�^�[��05';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN06 is '�p�^�[��06';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN07 is '�p�^�[��07';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN08 is '�p�^�[��08';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN09 is '�p�^�[��09';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN10 is '�p�^�[��10';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN11 is '�p�^�[��11';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN12 is '�p�^�[��12';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN13 is '�p�^�[��13';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN14 is '�p�^�[��14';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN15 is '�p�^�[��15';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN16 is '�p�^�[��16';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN17 is '�p�^�[��17';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN18 is '�p�^�[��18';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN19 is '�p�^�[��19';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN20 is '�p�^�[��20';
CREATE TABLE PUBLIC.MAIL_ATTACHED_FILE (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER NUMERIC(10) NOT NULL,
  FILE_NAME VARCHAR(150) NOT NULL,
  CONTENT_TYPE VARCHAR(50) NOT NULL,
  ATTACHED_FILE BYTEA NOT NULL,
  PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER)
);
COMMENT ON table PUBLIC.MAIL_ATTACHED_FILE is '���[���Y�t�t�@�C��';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.MAIL_REQUEST_ID is '���[�����M�v��ID';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.SERIAL_NUMBER is '�A��';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.FILE_NAME is '�Y�t�t�@�C����';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.CONTENT_TYPE is '�Y�t�t�@�C��CONTENT-TYPE';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.ATTACHED_FILE is '�Y�t�t�@�C��';
CREATE TABLE PUBLIC.MAIL_RECIPIENT (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER BIGINT NOT NULL,
  RECIPIENT_TYPE CHAR(1) NOT NULL,
  MAIL_ADDRESS VARCHAR(254) NOT NULL,
  PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER)
);
COMMENT ON table PUBLIC.MAIL_RECIPIENT is '���[�����M��';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.MAIL_REQUEST_ID is '���[�����M�v��ID';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.SERIAL_NUMBER is '�A��';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.RECIPIENT_TYPE is '���M��敪';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.MAIL_ADDRESS is '���[���A�h���X';
CREATE TABLE PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  MAIL_SEND_PATTERN_ID VARCHAR(2),
  SUBJECT VARCHAR(150) NOT NULL,
  MAIL_BODY VARCHAR(4000) NOT NULL,
  MAIL_FROM VARCHAR(254) NOT NULL,
  REPLY_TO VARCHAR(254) NOT NULL,
  RETURN_PATH VARCHAR(254) NOT NULL,
  CHARSET VARCHAR(50) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  REQUEST_DATETIME TIMESTAMP,
  SEND_DATETIME TIMESTAMP,
  PROCESS_ID CHAR(36),
  PRIMARY KEY (MAIL_REQUEST_ID)
);
COMMENT ON table PUBLIC.MAIL_REQUEST is '���[�����M�v��';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_REQUEST_ID is '���[�����M�v��ID';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_SEND_PATTERN_ID is '���[�����M�p�^�[��ID';
COMMENT ON column PUBLIC.MAIL_REQUEST.SUBJECT is '����';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_BODY is '�{��';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_FROM is '���M�҃��[���A�h���X';
COMMENT ON column PUBLIC.MAIL_REQUEST.REPLY_TO is '�ԐM�惁�[���A�h���X';
COMMENT ON column PUBLIC.MAIL_REQUEST.RETURN_PATH is '���߂��惁�[���A�h���X';
COMMENT ON column PUBLIC.MAIL_REQUEST.CHARSET is '�����Z�b�g';
COMMENT ON column PUBLIC.MAIL_REQUEST.STATUS is '�X�e�[�^�X';
COMMENT ON column PUBLIC.MAIL_REQUEST.REQUEST_DATETIME is '�v������';
COMMENT ON column PUBLIC.MAIL_REQUEST.SEND_DATETIME is '���M����';
COMMENT ON column PUBLIC.MAIL_REQUEST.PROCESS_ID is '�v���Z�XID';
CREATE TABLE PUBLIC.MAIL_TEMPLATE (
  MAIL_TEMPLATE_ID VARCHAR(10) NOT NULL,
  LANG CHAR(2) NOT NULL,
  SUBJECT VARCHAR(150) NOT NULL,
  MAIL_BODY TEXT NOT NULL,
  CHARSET VARCHAR(50) NOT NULL,
  PRIMARY KEY (MAIL_TEMPLATE_ID, LANG)
);
COMMENT ON table PUBLIC.MAIL_TEMPLATE is '���[���e���v���[�g';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.MAIL_TEMPLATE_ID is '���[���e���v���[�gID';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.LANG is '����';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.SUBJECT is '����';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.MAIL_BODY is '�{��';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.CHARSET is '�����Z�b�g';
CREATE TABLE PUBLIC.SAMPLE_USER (
  USER_INFO_ID CHAR(20) NOT NULL,
  LOGIN_ID VARCHAR(20) NOT NULL,
  KANJI_NAME VARCHAR(50) NOT NULL,
  KANA_NAME VARCHAR(50) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  PRIMARY KEY (USER_INFO_ID)
);
COMMENT ON table PUBLIC.SAMPLE_USER is '�T���v�����[�U���';
COMMENT ON column PUBLIC.SAMPLE_USER.USER_INFO_ID is '���[�U���ID';
COMMENT ON column PUBLIC.SAMPLE_USER.LOGIN_ID is '���O�C��ID';
COMMENT ON column PUBLIC.SAMPLE_USER.KANJI_NAME is '��������';
COMMENT ON column PUBLIC.SAMPLE_USER.KANA_NAME is '���Ȏ���';
COMMENT ON column PUBLIC.SAMPLE_USER.STATUS is '�����X�e�[�^�X';
ALTER TABLE PUBLIC.CODE_NAME
ADD
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES PUBLIC.CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);
ALTER TABLE PUBLIC.MAIL_ATTACHED_FILE
ADD
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID
);
ALTER TABLE PUBLIC.MAIL_RECIPIENT
ADD
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID
);
CREATE TABLE INS_PROJECT_SEND_MESSAGE
(
    SEND_MESSAGE_SEQUENCE           CHAR(10) NOT NULL,
    PROJECT_NAME                    VARCHAR(128) NOT NULL,
    PROJECT_TYPE                    VARCHAR(128) NOT NULL,
    PROJECT_CLASS                   VARCHAR(128) NOT NULL,
    PROJECT_START_DATE              DATE,
    PROJECT_END_DATE                DATE,
    CLIENT_ID                       NUMERIC(9,0),
    PROJECT_MANAGER                 VARCHAR(128),
    PROJECT_LEADER                  VARCHAR(128),
    USER_ID                         NUMERIC(9,0) NOT NULL,
    NOTE                            VARCHAR(512),
    SALES                           NUMERIC(9,0),
    COST_OF_GOODS_SOLD              NUMERIC(9,0),
    SGA                             NUMERIC(9,0),
    ALLOCATION_OF_CORP_EXPENSES     NUMERIC(9,0),
    STATUS                          CHAR(1),
    INSERT_USER_ID                  CHAR(10),
    INSERT_DATE                     TIMESTAMP,
    UPDATED_USER_ID                 CHAR(10),
    UPDATED_DATE                    TIMESTAMP(10),
    INSERT_REQUEST_ID               CHAR(30)
)
;
CREATE INDEX PRO_INS_REQ_ST_IDX
    ON INS_PROJECT_SEND_MESSAGE (STATUS)
;
ALTER TABLE INS_PROJECT_SEND_MESSAGE
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY  (SEND_MESSAGE_SEQUENCE)
;
CREATE TABLE INS_PROJECT_RECEIVE_MESSAGE
(
    RECEIVED_MESSAGE_SEQUENCE       CHAR(10) NOT NULL,
    PROJECT_NAME                    VARCHAR(128) NOT NULL,
    PROJECT_TYPE                    VARCHAR(128) NOT NULL,
    PROJECT_CLASS                   VARCHAR(128) NOT NULL,
    PROJECT_START_DATE              DATE,
    PROJECT_END_DATE                DATE,
    CLIENT_ID                       NUMERIC(9,0),
    PROJECT_MANAGER                 VARCHAR(128),
    PROJECT_LEADER                  VARCHAR(128),
    USER_ID                         NUMERIC(9,0) NOT NULL,
    NOTE                            VARCHAR(512),
    SALES                           NUMERIC(9,0),
    COST_OF_GOODS_SOLD              NUMERIC(9,0),
    SGA                             NUMERIC(9,0),
    ALLOCATION_OF_CORP_EXPENSES     NUMERIC(9,0),
    STATUS                          CHAR(1),
    INSERT_USER_ID                  CHAR(10),
    INSERT_DATE                     TIMESTAMP,
    UPDATED_USER_ID                 CHAR(10),
    UPDATED_DATE                    TIMESTAMP,
    INSERT_REQUEST_ID               CHAR(30)
)
;
CREATE INDEX PRO_TEMP_ST_IDX
    ON INS_PROJECT_RECEIVE_MESSAGE (STATUS)
;
ALTER TABLE INS_PROJECT_RECEIVE_MESSAGE
    ADD CONSTRAINT PK_PROJECT2 PRIMARY KEY  (RECEIVED_MESSAGE_SEQUENCE)
;
CREATE TABLE ID_GENERATE
(
    GENERATOR_ID                    VARCHAR(30) NOT NULL,
    GENERATED_NO                    NUMERIC(10,0) NOT NULL
)
;
ALTER TABLE ID_GENERATE
    ADD CONSTRAINT PK_ID_GENERATE PRIMARY KEY  (GENERATOR_ID)
;